version: "3"
services:
  app:
    build: .
    container_name: reports
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host-local.docker.internal:172.17.0.1"
    networks:
      - my-network

networks:
  my-network:
    external: true
