GET http://localhost:3000/transactions

###
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "payment_date":"2023-08-04",
  "name": "NOva",
  "description": "Descrição da despesa",
  "category": "category1",
  "amount": 30,
  "type": "debit"
}