version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - development-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - '.:/home/node/app'
    depends_on:
      - db

  db:
    build: ./.docker/db
    restart: always
    tty: true
    volumes:
      - './.docker/dbdata:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - development-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
networks:
  development-network:
    driver: bridge
