version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always,
    tty: true,
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
