version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3000'
    networks:
      - arquitetura-network
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - '.:/home/node/app'
    extra_hosts:
      - 'host-local.docker.internal:172.17.0.1'
networks:
  arquitetura-network:
    driver: bridge
